### ISSUE TITLE
App demo crash at first loading

### ISSUE THREAD

**Issue by nhan7777** [ernesto-elsaesser/OfflineWebView#1]
dyld: Library not loaded: @rpath/WebArchiver.framework/WebArchiver
  Referenced from: /var/containers/Bundle/Application/FFB31E2B-8F42-41AA-B20A-AD82FA7F1420/OfflineWebView.app/OfflineWebView
  Reason: image not found

I did deintegrate pod and install it again. But issue still be there. I use xCode 10.1, Swift 4.2

**Comment by ernesto-elsaesser** [comment]
My bad, broke the Podfile when separating the `WebArchiver` framework from the app.
The latest commit should fix your issue. `git clone` + `pod install` should be sufficient to run the app on a simulator. Please let me know if this solved your problem 👍
