### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by camh** [ernesto-elsaesser/OfflineWebView#2]
Sorry, I didn't see a way to contact you other than LinkedIn.

I'm writing a free iOS utility to view and create web archives … cause I recently took my iPad on a trip as my sole computer and was absolutely astonished there's no way to view web archives on iOS, much less create them!

Anyways, you didn't include a license so I wanted to ask if I could include your clever web archiver in my app. It's the only way I've found to reliably create web archives on iOS since calling `copy(:)` on `WKWebView` … doesn't really work, ugh. If not, I can create my own web archiver.

Cheers!

**Comment by ernesto-elsaesser** [comment]
Hey @camh, thanks for asking!
I added an MIT license: https://github.com/ernesto-elsaesser/OfflineWebView/blob/master/LICENSE
Would love to see the utility when it's ready :)

**Comment by camh** [comment]
Great, thank you! I'll let you know when it's ready
