### ISSUE TITLE
Not working for Ajax based content of Webpage

### ISSUE THREAD

**Issue by TheMrugraj** [ernesto-elsaesser/OfflineWebView#3]
Library is working decent for normal content. but, its failing where AJAX based content loading is taking place. e.g https://ieeexplore.ieee.org/document/7185326

Here in above URL actual article is being fetched using JS Call on scrolling. So, if I archive it and try to open in offline it is not displaying that content part. So, is it feasible to Save whatever is displayed in WKWebView in the same form.

**Comment by ernesto-elsaesser** [comment]
Hello Mrugrajsinh, thanks for your feedback! You are right, the created archives only include hard-linked i.e. static resources. Unfortunately this is a technical limitation of the archiving approach itself. Web applications which dynamically fetch content can not really be archived into a single file without reverse engineering the application or including the full backend. Theoretically it would be possible to parse JavaScript resources for network requests and archive the target URLs as well, but this would introduce a couple of new problems and would also be very error-prone.

A far better approach to make a dynamic web application available offline would be to simply configure caching to cache every single request. Unfortunately, I didn't find a good way to configure a WKWebView in such a way. Actually that was the reason why I wrote the archiver in the first place.
